//
//  ShowPodcastPresenter.swift
//  TopPodcasts
//
//  Created by Sander Korebrits on 17/08/2018.
//  Copyright (c) 2018 designlapp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowPodcastPresentationLogic{
    func presentGetPodcast(response: ShowPodcast.GetPodcast.Response)
}

class ShowPodcastPresenter: ShowPodcastPresentationLogic{
    weak var viewController: ShowPodcastDisplayLogic?
  
    func presentGetPodcast(response: ShowPodcast.GetPodcast.Response){
        let artistName = response.podcast.artistName ?? ""
        let copyright = response.podcast.copyright ?? ""
        let name = response.podcast.name ?? ""
        let releaseDate = response.podcast.releaseDate ?? ""
        let genres = (response.podcast.genres.compactMap({ $0.name })).joined(separator: " ")
        let viewModel = ShowPodcast.GetPodcast.ViewModel(artistName: artistName,
                                                         copyright: copyright,
                                                         name: name,
                                                         releaseDate: releaseDate,
                                                         genres: genres)
        
        viewController?.displayGetPodcast(viewModel: viewModel)
    }
}
