//
//  ShowPodcastRouter.swift
//  TopPodcasts
//
//  Created by Sander Korebrits on 17/08/2018.
//  Copyright (c) 2018 designlapp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowPodcastRoutingLogic{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ShowPodcastDataPassing{
    var dataStore: ShowPodcastDataStore? { get }
}

class ShowPodcastRouter: NSObject, ShowPodcastRoutingLogic, ShowPodcastDataPassing{
    weak var viewController: ShowPodcastViewController?
    var dataStore: ShowPodcastDataStore?
  
    // MARK: Routing

    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}

    // MARK: Navigation

    //func navigateToSomewhere(source: ShowPodcastViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}

    // MARK: Passing data

    //func passDataToSomewhere(source: ShowPodcastDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
