//
//  ShowPodcastInteractor.swift
//  TopPodcasts
//
//  Created by Sander Korebrits on 17/08/2018.
//  Copyright (c) 2018 designlapp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowPodcastBusinessLogic{
    func getPodcast(request: ShowPodcast.GetPodcast.Request)
}

protocol ShowPodcastDataStore{
    var podcast: Podcast? { get set }
}

class ShowPodcastInteractor: ShowPodcastBusinessLogic, ShowPodcastDataStore{
    var presenter: ShowPodcastPresentationLogic?
    var podcast: Podcast?
    //var worker: ShowPodcastWorker?

    func getPodcast(request: ShowPodcast.GetPodcast.Request){
        //worker = ShowPodcastWorker()
        //worker?.doSomeWork()
        guard let podcast = podcast else{
            return
        }
        let response = ShowPodcast.GetPodcast.Response(podcast: podcast)
        presenter?.presentGetPodcast(response: response)
  }
}
