//
//  ShowPodcastInteractorTests.swift
//  TopPodcasts
//
//  Created by Sander Korebrits on 17/08/2018.
//  Copyright (c) 2018 designlapp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TopPodcasts
import XCTest

class ShowPodcastInteractorTests: XCTestCase{
    
    // MARK: Subject under test
    var sut: ShowPodcastInteractor!
  
    // MARK: Test lifecycle
    override func setUp(){
        super.setUp()
        setupShowPodcastInteractor()
    }
  
    override func tearDown(){
        super.tearDown()
    }
  
    // MARK: Test setup
    func setupShowPodcastInteractor(){
        sut = ShowPodcastInteractor()
    }
  
    // MARK: Test doubles
    class ShowPodcastPresentationLogicSpy: ShowPodcastPresentationLogic{
        var presentGetPodcastCalled = false
    
        func presentGetPodcast(response: ShowPodcast.GetPodcast.Response){
            presentGetPodcastCalled = true
        }
    }
  
    // MARK: Tests
    func testGetPodcast(){
        // Given
        let spy = ShowPodcastPresentationLogicSpy()
        sut.presenter = spy
        sut.podcast = Podcast.emptyPodcast()
        let request = ShowPodcast.GetPodcast.Request()
    
        // When
        sut.getPodcast(request: request)
    
        // Then
        XCTAssertTrue(spy.presentGetPodcastCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
