//
//  ShowPodcastWorkerTests.swift
//  TopPodcasts
//
//  Created by Sander Korebrits on 17/08/2018.
//  Copyright (c) 2018 designlapp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TopPodcasts
import XCTest

class ShowPodcastWorkerTests: XCTestCase{
  
    // MARK: Subject under test
    var sut: ShowPodcastWorker!
  
    // MARK: Test lifecycle
    override func setUp(){
        super.setUp()
        setupShowPodcastWorker()
    }

    override func tearDown(){
        super.tearDown()
    }

    // MARK: Test setup

    func setupShowPodcastWorker(){
        sut = ShowPodcastWorker()
    }

    // MARK: Test doubles

    // MARK: Tests
    func testSomething(){
        // Given

        // When

        // Then
    }
}
