//
//  ShowPodcastViewControllerTests.swift
//  TopPodcasts
//
//  Created by Sander Korebrits on 17/08/2018.
//  Copyright (c) 2018 designlapp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TopPodcasts
import XCTest

class ShowPodcastViewControllerTests: XCTestCase{
    
    // MARK: Subject under test
    var sut: ShowPodcastViewController!
    var window: UIWindow!

    // MARK: Test lifecycle
    override func setUp(){
        super.setUp()
        window = UIWindow()
        setupShowPodcastViewController()
    }

    override func tearDown(){
        window = nil
        super.tearDown()
    }

    // MARK: Test setup
    func setupShowPodcastViewController(){
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "ShowPodcastViewController") as! ShowPodcastViewController
    }

    func loadView(){
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }

    // MARK: Test doubles
    class ShowPodcastBusinessLogicSpy: ShowPodcastBusinessLogic{
        var getPodcastCalled = false

        func getPodcast(request: ShowPodcast.GetPodcast.Request){
            getPodcastCalled = true
        }
    }

    // MARK: Tests
    func testShouldDoSomethingWhenViewIsLoaded(){
        // Given
        let spy = ShowPodcastBusinessLogicSpy()
        sut.interactor = spy

        // When
        loadView()

        // Then
        XCTAssertTrue(spy.getPodcastCalled, "viewDidLoad() should ask the interactor to do something")
    }

    func testDisplaySomething(){
        // Given
        let viewModel = ShowPodcast.GetPodcast.ViewModel.emptyViewModel()

        // When
        loadView()
        sut.displayGetPodcast(viewModel: viewModel)

        // Then
        //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
    }
}
