//
//  ListPodcastsRouter.swift
//  TopPodcasts
//
//  Created by Sander Korebrits on 17/08/2018.
//  Copyright (c) 2018 designlapp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListPodcastsRoutingLogic{
    func routeToShowPodcast(segue: UIStoryboardSegue?)
}

protocol ListPodcastsDataPassing{
    var dataStore: ListPodcastsDataStore? { get }
}

class ListPodcastsRouter: NSObject, ListPodcastsRoutingLogic, ListPodcastsDataPassing{
    weak var viewController: ListPodcastsViewController?
    var dataStore: ListPodcastsDataStore?
  
    // MARK: Routing
    func routeToShowPodcast(segue: UIStoryboardSegue?){
        if let segue = segue,
            let dataStore = dataStore,
            let destinationVC = segue.destination as? ShowPodcastViewController{
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowPodcasts(source: dataStore, destination: &destinationDS)
        }else{
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            if let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowPodcastViewController") as? ShowPodcastViewController,
                let dataStore = dataStore,
                let viewController = viewController{
                var destinationDS = destinationVC.router!.dataStore!
                passDataToShowPodcasts(source: dataStore, destination: &destinationDS)
                navigateToShowPodcast(source: viewController, destination: destinationVC)
            }
        }
    }
    
    func passDataToShowPodcasts(source: ListPodcastsDataStore, destination: inout ShowPodcastDataStore){
        guard let indexPath = viewController?.collectionView.indexPathsForSelectedItems?.first else{
            return
        }
        destination.podcast = source.podcasts[indexPath.row]
    }
    
    func navigateToShowPodcast(source: ListPodcastsViewController, destination: ShowPodcastViewController){
        source.show(destination, sender: nil)
    }
}
