//
//  ListPodcastsModels.swift
//  TopPodcasts
//
//  Created by Sander Korebrits on 17/08/2018.
//  Copyright (c) 2018 designlapp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListPodcasts{
    // MARK: Use cases
    
    
    enum ListPodcasts{
        struct Request{
            
        }

        struct Response{
            var podcasts: [Podcast]
            var success: Bool
            var error: ItunesService.ItunesServiceError?
        }

        struct ViewModel{
            struct CellDisplayModel{
                var name: String
                var image: UIImage?
            }
            struct ErrorDisplayModel{
                var message: String
            }
            var displayModels: [CellDisplayModel]
            var errorDisplayModel: ErrorDisplayModel?
        }
    }
    
    enum FetchImage{
        struct Request{
            let row: Int
        }
        
        struct Response{
            var podcast: Podcast
            var row: Int
            var success: Bool
            var error: ItunesService.ItunesServiceError?
        }
        
        struct ViewModel{
            var response: Response
            var displayModel: ListPodcasts.ViewModel.CellDisplayModel
        }
    }
}
