//
//  ListPodcastsModels.swift
//  TopPodcasts
//
//  Created by Sander Korebrits on 17/08/2018.
//  Copyright (c) 2018 designlapp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListPodcasts{
  // MARK: Use cases
  enum ListPodcasts{
    struct Request{
        
    }
    
    struct Response{
        var podcasts: [Podcast]
        var success: Bool
        var errorMessage: String?
    }
    
    struct ViewModel{
        struct CellDisplayModel{
            var name: String
            var image: UIImage?
        }
        var response: Response
        var displayModels: [CellDisplayModel]
    }
  }
}
