//
//  ListPodcastsInteractor.swift
//  TopPodcasts
//
//  Created by Sander Korebrits on 17/08/2018.
//  Copyright (c) 2018 designlapp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPodcastsBusinessLogic{
    func listPodcasts(request: ListPodcasts.ListPodcasts.Request)
}

protocol ListPodcastsDataStore{
    var podcasts: [Podcast] { get }
}

class ListPodcastsInteractor: ListPodcastsBusinessLogic, ListPodcastsDataStore{
    var presenter: ListPodcastsPresentationLogic?
    var worker: ListPodcastsWorker?
    var podcasts: [Podcast] = []
    
    func listPodcasts(request: ListPodcasts.ListPodcasts.Request){
        worker = ListPodcastsWorker()
        worker?.listPodcasts(completion: { [weak self] (succes, podcasts, errorMessage) in
            self?.podcasts = podcasts
            let response = ListPodcasts.ListPodcasts.Response(podcasts: podcasts, success: succes, errorMessage: errorMessage)
            self?.presenter?.presentListPodcasts(response: response)
        })
  }
}
