//
//  ListPodcastsWorker.swift
//  TopPodcasts
//
//  Created by Sander Korebrits on 17/08/2018.
//  Copyright (c) 2018 designlapp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListPodcastsWorker{
    func listPodcasts(completion: @escaping (_ succes: Bool, _ podcasts: [Podcast], _ errorMessage: String?) -> Void){
        ItunesService.fetchTopPodcasts { (result) in
            switch result{
            case .success(let feed):
                completion(true, feed.results, nil)
            case .error(let error):
                switch error{
                case .malformdJSON:
                    completion(false, [], ErrorMessage.ItunesService.malformedJSON.str)
                case .network:
                    completion(false, [], ErrorMessage.ItunesService.networkError.str)
                }
            }
        }
    }
}
