//
//  ListPodcastsWorker.swift
//  TopPodcasts
//
//  Created by Sander Korebrits on 17/08/2018.
//  Copyright (c) 2018 designlapp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListPodcastsWorker{
    func listPodcasts(completion: @escaping (_ succes: Bool, _ podcasts: [Podcast], _ error: ItunesService.ItunesServiceError?) -> Void){
        ItunesService.fetchTopPodcasts { (result) in
            switch result{
            case .success(let feed):
                completion(true, feed.results, nil)
            case .error(let error):
                completion(false, [], error)
            }
        }
    }
    
    func fetchImageArtwork(url: String, completion: @escaping (_ succes: Bool, _ artworkImage: UIImage?, _ error: ItunesService.ItunesServiceError?) -> Void){
        ItunesService.fetchImage(url: url) { (result) in
            switch result{
            case .success(let image):
                completion(true, image, nil)
            case .error(let error):
                completion(false, nil, error)
            }
        }
    }
}
